Suchitra-Sahoo/AgriLearnNetwork

index.html, style.css
fixed the issue of image moving again and again with the text growing and shrinking 
also there was the word "to" missing in the text now the UI seems correct until I raise more issues , thankyou
=> fixed the raised issue, added a missing word "to" to make the text correct

index.html, style.css
**Description:**
This pull request addresses the following changes in the footer:
**Screenshots (if applicable):**
**Additional Notes:**
(Optional: Add any additional information or context relevant to the changes made.)
**Checklist:**
**Related Issues:**
Closes #13
**Reviewer(s):**
@Suchitra-Sahoo @kairveeehh
=> Update Footer Alignment with Website Theme (#13)

contributing.md
=> Created CONTRIBUTING.md File

index.html
=> Updated the chatbot with Visible close button, better styling and size

script.js, style.css
Changed Home navbar color to white to appear on the website and when home is clicked it will appear to green
=> Changed Home navbar color issue #52

index.html, script.js, style.css
Here we gooooooooooooooo
Made web page font style standard
Well designed contact form
Responsive form
Alert form
=> Contact-form-responsive

index.html, script.js, style.css
Reverts Suchitra-Sahoo/AgriLearnNetwork#112
=> Revert "Contact-form-responsive"

index.html, style.css
#18  added the tooltip to make mail id visible on hover , without conflicts
=> fixed #18 added tooltips

index.html, script.js, style.css
The nav link to the contacts section is added and previous when i clicked on any of the nav link the nav link remains active even if i scrolled to another section, i have added event listeners to each of the section (home, about, blogs, resource library and contact), what happens by doing this is when you click on any of the nav link the nav link is active only until and unless scrolled to another section,  when one nav link is active and if we scroll to another section the nav link corresponding to the current section become active and the previously activated nav link gets deactivated resulting in better user experience
Thank You @Suchitra-Sahoo for assigning this project to me under GSSoC 2024
It was such an amazing experience for me adding some features to this project
Once again …
=> Added the nav link of contact section to the nav bar and updated the behavior of nav links upon scrolling over sections

style.css
Hello PA,
Fixed issue  number - #21
Screenshot-
Comparison of after and before
Now it neither mixes with the multiple background images  nor with the white background color
=> added text shadow along with new color #21

index.html, script.js, style.css
I have enhance the UI of the form and the form now resets after submit and also hide the scroll bar for better view and also i have added custom validations which input tags cant handle
=> UI Enhancing and form reseting after submit

index.html, style.css
Pull req [#137 ](url)
Screenshot added on the pull request itself. Kindly check. 
NB: I am a contributor of GSSOC'24. Kindly check my pull request.
=> Made the scroll bar sleek with disappearing track

index.html, style.css
Reverts Suchitra-Sahoo/AgriLearnNetwork#192
=> Revert "Fixes Issue #162 Improved UI/UX agro blogs section"

style.css
This pull request enhances the footer section by adding a hover effect to the social media icons and ensuring their proper horizontal centering within the container.
Fixes: #141
Changes:
1) Implemented a hover effect on the social media icons to provide visual feedback to users when interacting with them.
2) Adjusted the CSS to center the icons horizontally within the footer section, improving the overall alignment and aesthetics.
Details:
1) The hover effect was achieved through CSS transitions, making the icons change color or scale slightly when hovered over.
2) Leveraged CSS flexbox properties to ensure that the icons are centered regardless of the screen size or device orientation.
3) Tested the changes across different browsers and screen resolutions to ensure compatibility and …
=> Hover effect on social icons added

index.html
In Agro Blogs section, instead of click on heading to redirect to respective page, I have improved it such that upon clicking on ('div') service box, redirection happens to respective blogs.
=> Issue#69: Enhance cards to redirect to webpage upon clicking.

index.html
Reverts Suchitra-Sahoo/AgriLearnNetwork#208
=> Revert "Update footer copyright year to be dynamic"

index.html
Fixes: #147 
From
to
I have tried to keep the design as similar as possible but there are not enough customizations available to keep the design the same. Also please check your mail for working video.
=> Feat: Enhance the AI ChatBot Working #147

index.html, script.js, style.css
made changes and created the feedback form again using modal class.
now i have encapsulated the entire js into one single function to avoid any kind of conflict.
please tell if you want any modifications.
thankyou.
=> feedback form add

style.css
#191 Text is Justified for all devices .
Text is justified from both the sides as Justify from both the sides for large and medium displays.
Text is justified from both the sides as Center from both the sides for small devices.
=> Aligned Text FIXED #191 Justification of text .

index.html
Fixed issue #179 
- Updated the footer to use JavaScript to dynamically display the current year.
- Replaced the static year with <script>document.write(new Date().getFullYear())</script> to ensure the year is always up to date.
This pull request updates the footer to display the current year dynamically using JavaScript.
=> Update footer to display current year dynamically

index.html, script.js, style.css
I have changed the design of mouse follower and made it look even more better for the agricultural theme 
https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/140224513/ea2f091a-7752-491a-98e3-558a1a9dd792
My PR fixes #218 issue. @Suchitra-Sahoo Kindly check it and merge it, Thankyou😊
=> Mouse follower added and design changed

index.html, script.js, style.css
Reverts Suchitra-Sahoo/AgriLearnNetwork#234
=> Revert "Mouse follower added and design changed"

index.html
Updated the below PR.
https://github.com/Suchitra-Sahoo/AgriLearnNetwork/pull/171
=> Issue#69: Redirect upon clicking cards, not only upon clicking title.

style.css
Issue #233 
Increased margin between blogs and the title making it look better when we hover on the blogs.
=> Increase margin between blogs and title

index.html, script.js, style.css
Reverts Suchitra-Sahoo/AgriLearnNetwork#253
=> Revert "Image gallery"

style.css
=> REMOVED EXTRA SPACE BETWEEN PAGE END AND NAVBAR LIST ITEM

style.css
Closes #255 
Fixed feedback form centered the stars and submit button
- [] Bug fix (non-breaking change which fixes an issue)
I have checked locally on my pc
- [] My code follows the style guidelines of this project
- [] I have performed a self-review of my own code
- [] I am an Open Source Contributor
=> Fixed feedaback form stars and submit button

index.html, style.css
This pull request, my first contribution, addresses alignment issues within the navbar section of our application. It enhances the user experience by ensuring consistency and visual appeal across different screen sizes and devices.
**before** 
**after** 
Additional Notes:
- this is my first pull request , so please make sure to highlight if any mistakes are present
=> made changes in navbar section - allignment  resolving issue #301

index.html, style.css
Reverts Suchitra-Sahoo/AgriLearnNetwork#302
=> Revert "made changes in navbar section - allignment  resolving issue #301"

README.md
@Suchitra-Sahoo ...I have added "Let's Get Started" content below website overview, keeping the rest whole readme.md as it is. Kindly review and merge
=> Added "Lets Get Started" in readme.md

index.html
Fixes: #329 
From:
https://private-user-images.githubusercontent.com/133234867/331283488-2c5b9250-f22a-4aa7-8618-b1664d09d7c6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU4NzgyOTYsIm5iZiI6MTcxNTg3Nzk5NiwicGF0aCI6Ii8xMzMyMzQ4NjcvMzMxMjgzNDg4LTJjNWI5MjUwLWYyMmEtNGFhNy04NjE4LWIxNjY0ZDA5ZDdjNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxNlQxNjQ2MzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zZTgyNWMyZGYwZGVkYThlNjFkMWZkYWIxNmFhYjIzY2VhMzkwOWYxOWZiNDIyOWFjNGQzZjQwMjhlMTE0NjVhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Gq0K …
=> [FEAT]: Enhanced ChatBot

index.html, style.css
I have added a video to the about section and made some UI changes to align it with the home page. The video file, 'Agriculturevideo.mp4,' has been placed in the root directory. 
https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/140971159/e5461e37-a327-46fd-959e-68dc211aacb8
=> Background Video added in the about section issue #256

index.html
https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/111896909/520ab351-e5de-48c4-bc51-3a1b34d2332c
=> Issue 145 resolved

README.md
@Suchitra-Sahoo ...I have left-aligned let's get started content 
Key-features changes done!
Shall I make it left-aligned too for enhancement or above is fine?...It will look like below then
=> Enhanced readme.md #63

index.html, style.css
I have adjusted the font size of the texts to fit the screen size. Currently, I am working on removing the gap between the carousel and the about section video, as well as changing the backgrounds of other sections. Issue #256.
=> Adjusted the font size of text for mobile screens.

index.html, style.css
Reverts Suchitra-Sahoo/AgriLearnNetwork#356
=> Revert "Adjusted the font size of text for mobile screens."

index.html, style.css
Reverts Suchitra-Sahoo/AgriLearnNetwork#189
=> Revert "contact page enhanced"

index.html, style.css
Carousel Component is added.  After adding the bootstrap cdn link, there is some change in the font-weights of different headongs. So, I changed the font-size and font-weights in order to have the previous view of the webpage.
Here is the video demonstrating the changes, I made in the website.
https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/114400934/821f65c7-1405-4b9e-9645-1b8014d4c116
=> Resolved #321,Carousel Component is added instead of a slideshow in home page

index.html, style.css
Reverts Suchitra-Sahoo/AgriLearnNetwork#374
=> Revert "Resolved #321,Carousel Component is added instead of a slideshow in home page"

index.html, style.css
#268 fixing according to discussion
=> Date time-alignment on blog card design

CropYieldCalculator.html, index.html, script.js, style.css
A Crop Yield Calculator is a tool used to estimate the potential yield of a crop based on various factors that affect crop growth and productivity. It's a valuable resource for farmers, agricultural professionals, and researchers to predict and optimize crop yields, making informed decisions about planting, harvesting, and resource allocation.
It calculates the expected crop yield by taking crop type ,weather condition soil type as input ,management practices ,crop rotation ,area into consideration.
Changes I have made-
1. Added a Crop yield calculator 
2. Updated the front-end with a new section in the dashboard for the crop yield calculator.
3. Also updated the quick-links
=> CROP YIELD CALCULATOR

index.html, style.css
The code is upto date with the main branch, ive added te text on the images before hovering the youtube videos
the video is in comments
=> Issue 349 solved

style.css
Issue : #372 
I did some changes in the styling of navbar and the header to make it responsive .
https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/118350936/d5de2a94-2374-4572-9c7e-3ec78008fb85
=> Navbar Responsiveness  #372

index.html, style.css
Hello PA,
Fixed issue no - #383
I changed into the style.css file and index.html file.
Before the blog section was not well arranged so i arranged the whole blog section very well.
Make the blog section horizontally scrollable,  which makes the website user friendly.
=> Add horizontal scroller into blog section    #383

index.html, style.css
Reverts Suchitra-Sahoo/AgriLearnNetwork#426
=> Revert "Add horizontal scroller into blog section    #383"

script.js, style.css
Closes #431 
Fixed feedback form.
And fixed some bugs in About section & Resource Library section
=> Fixed some css bugs and Feedback form

script.js, style.css
fixed #420 
I have successfully added a drop down animation of navbar for tab and mobile devices. On clicking the menu icon the navItems drop down with a smooth animation. Additionally I have made the hover of mouse on Menu to be Pointer 
- [✅] Bug fix
- [✅] Feature enhancement
- [❌ ] Documentation update
- [ ❌] Other (specify): _______________
https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/83546205/f4a2cb2d-0b92-4852-b748-ac9b6b9ea2ee
- [✅] I have performed a self-review of my code
- [✅] I have read and followed the Contribution Guidelines.
- [✅] I have …
=> nav animation is done

script.js, style.css
Reverts Suchitra-Sahoo/AgriLearnNetwork#454
=> Revert "nav animation is done"

blogpage/index.html, blogpage/style.css, index.html
#463 
Made required changes u mentioned.
https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/109607812/379c1cb8-b694-42a6-a96b-c284f7148b19
=> made changes to Blog Page and main page

index.html, style.css
Reverts Suchitra-Sahoo/AgriLearnNetwork#493
=> Revert "pre loader"

index.html, style.css
Reverts Suchitra-Sahoo/AgriLearnNetwork#472
=> Revert "Enhanced Feedback form"

index.html, style.css
Feat: Back To Top Button Should be Fixed #529
As i mentioned in issue that Back top top button's Css is changed and i put it fixd and top of chatbot button and
also make sure that when we are on top that time top button eill not be visible and on scrolling it would be visible 
i have done it using js
I just changes css of the button 
and for it's visibility added 1 js function it is not affecting other code
=> top button css updated

blogpagestyle.css
#502 BUG: Cards are not responsive for small screen sizes #502 is solved 
Aligned the date and time in cards in blogs properly
@Suchitra-Sahoo I am contributing under GSSoC 2024 Please label this PR
=> Changed the style of the card to make it responsive in small screen sizes  #502

index.html, style.css
#451 
Now its enhanced
- [x ] Feature enhancement
- [x ] I have performed a self-review of my code
- [x ] I have read and followed the Contribution Guidelines.
- [x ] I have tested the changes thoroughly before submitting this pull request.
- [x ] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x ] I have commented my code, particularly in hard-to-understand areas.
=> feedback form

index.html, style.css
Fixes #498 
When scrolled , the navbar changes colour and has swift animations and sticky effect. In this, the navbar is made more readable even when scrolled to contacts and resources sections.
(if you need to change color, we can change, I couldn't find more colors on the existing CSS)
https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/146661411/86f7a622-b47b-4a75-8cf0-544cd96bec57
=> NavBar animations, responsiveness on scroll

index.html, style.css
Change CSS properties to style the feedback button
closes #553  @Suchitra-Sahoo
=> Styled feedback button

index.html, script.js, style.css
#482 
A subscribe button with newsletter feature is added in the footer
=> newsletter is added in footer

index.html, script.js, style.css
Reverts Suchitra-Sahoo/AgriLearnNetwork#548
=> Revert "newsletter is added in footer"

.vscode/settings.json, style.css
Reverts Suchitra-Sahoo/AgriLearnNetwork#538
=> Revert "Change in style of home page"

index.html, script.js
I've added a message saying 'Thank you for your feedback!' in green color, which appears after submitting the feedback form instead of displaying an alert. This provides a smoother user experience. Additionally, if the user submits the form without selecting any star rating, a message 'Please fill in all fields before submitting.' in red color will be displayed. This immediate feedback ensures that users notice any missing information right away.
=> Feedback messages submit style updated instead of give alert. 

index.html, script.js, style.css
Reverts Suchitra-Sahoo/AgriLearnNetwork#517
=> Revert "#488 Submit button to disable unless all fields are filled"

index.html, script.js, style.css
#486 
https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/158484284/02900be0-8559-406f-9ba2-4457871aadb7
https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/158484284/513effc4-aca1-4058-936f-f7b6eb25834e
=> pre- loader

blogpagestyle.css
issue no #579 
I have added styles to the search bar and search icon so that users can feel that the search icon is functional. I incorporated transitions and a scale effect when the search icon is clicked. I did my best to style it and enhance the UI.
**I dedicated significant effort to styling this, aiming to create a better UI. Your acknowledgment and appreciation for my hard work mean a lot. Please consider this as level2 Thank you!**
=> Style added to Searchbar and Search-icon

index.html, login.css, login.html, login.js, script.js, style.css
https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/145560431/7b3b5d76-f1e8-4e2e-b54c-f6cd940fe1ab
Added login/registration feature
I have added a login/register button which will direct the user to a login/registration page.
##Feature Enhancement
=> Added login/registration feature

blogpagestyle.css
=> scrollbar styled in the blog page

blogpage.html, blogpagestyle.css
Reverts Suchitra-Sahoo/AgriLearnNetwork#648
=> Revert "Navbar added in about page"

blogpage.html, blogpagestyle.css, style.css
resolves #545 
- [] Bug fix
- [ x] Feature enhancement
- [ x] I have performed a self-review of my code
- [ x] I have read and followed the Contribution Guidelines.
- [ x] I have tested the changes thoroughly before submitting this pull request.
- [ x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [ x] I have commented my code, particularly in hard-to-understand areas.
=> Navbar of about page updated again

style.css
In Footer Social media icons transform scale feature. Please assign me this task where I will add transform scale feature in footer social media icons . I add videos first before and after transform scale feature. Assign me this under gssoc'2024.
#634 
[Footer social media Icons hover transform and transition feature.”]
In Footer Social media icons transform scale feature.
Please assign me this task where I will add transform scale feature in footer social media icons .
I add videos first before and after transform scale feature.
Assign me this under gssoc'2024.
1. Before adding -
https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/136844498/2e3b3b19-0fdf-40f4-a158-4427c9ff3c00
2. After adding-
https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/136844498/5641f473-270d-404b-bbd …
=> Footer social media Icons hover transform and transition feature.

style.css
[Please include a brief description of the changes or features added] :-Added cursor pointer on login button
https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/149527268/5e76b578-fc72-4534-821d-0f80ceb8e877
https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/149527268/22ba72e9-132d-4b44-adf7-6776e90b957e
=> login btn cursor pointer/added cursor pointer on login button

blogpage.html, blogpagestyle.css
Fixes #694 
Tabs of the navbar in blog page are not aligned properly . I have solved the issue and  fixed the tabs at proper place.
- Bug fix
-----
- I have performed a self-review of my code
- I have read and followed the Contribution Guidelines.
- I have tested the changes thoroughly before submitting this pull request.
- I have provided relevant issue numbers, screenshots after making the changes.
- I have commented my code, particularly in hard-to-understand areas.
-----
<h3>Kindly  merge it and please give the label of gssoc and level for both issue and PR.</h3>
=> fix #694 : fixed the navbar tabs issue 

blogpage.html, blogpagestyle.css
Reverts Suchitra-Sahoo/AgriLearnNetwork#701
=> Revert "fix #694 : fixed the navbar tabs issue "

blogpage.html, blogpagestyle.css
Fixes issue #695 
Made navbar look good without overlapping with other content and also made toggle bar clickable to view menu.
https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/121669832/a311392c-4b84-4e88-84f1-334a981db690
Please check it and let me know if any changes, Thank you.
=> Fix: Made header look good.

blogpage.html, blogpagestyle.css
Tabs of the navbar in blog page are not aligned properly and are not responsive. I have solved the issue and  fixed the tabs at proper place and made responsive.
Fixes #694 
- Bug fix
-----
https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/166977453/5ab12bdc-bf1a-4fbb-b26d-161ce95066c1
-----
-----
- I have performed a self-review of my code
- I have read and followed the Contribution Guidelines.
- I have tested the changes thoroughly before submitting this pull request.
- I have provided relevant issue numbers, screenshots after making the changes.
- I have commented my code, particularly in hard-to-understand areas.
-----
<h3>Kindly  merge it and please give the label of gssoc and level for both issue and PR.</h3>
=> Fixed navbar and made responsive 

blogpage.html, blogpagestyle.css
Reverts Suchitra-Sahoo/AgriLearnNetwork#725
=> Revert "Fixed navbar and made responsive "

style.css
fixes #686 
In this the ``login`` button was not in correct place it looking like this 
**After Fix **
it is looking like this 
=> fix: the login/register button in wrong place

index.html, style.css
#700
In this I have adjust the size of logo according to website
=> Increase the size of the Logo

index.html, style.css
Reverts Suchitra-Sahoo/AgriLearnNetwork#724
=> Revert "Increase the size of the Logo"

login.css, login.html, login.js
Added all required
For reference :- 
@Suchitra-Sahoo please have a look
=> Add header, footer in login and redirect to home after login

login.html
=> Added social icons in footer of login page

script.js
None
The provided code snippet was modified to fix an error related to the header.classList being undefined. The fix involves changing how the header element is selected to ensure it refers to a single element rather than a NodeList. 
- [x ] Bug fix
This resolves the bug  Uncaught TypeError: header.classList is undefined
=> Fixes #698  Uncaught TypeError: header.classList is undefined

blogpage.html, blogpagestyle.css, style.css
None
As mentioned in issue #732 the elements of the blog navbar and home navbar are not correctly positioned. I have fixed that issue for both pages the supporting screenshots are attached below. Kindly review this and let me know if I can add more things. 
**BEFORE HOME PAGE**
Before the login button was not at its place which is now fixed.
When we hover on login button the Register button was not clearly visible.
**AFTER HOME PAGE**
Login button and Register button are now clearly visible.
**BEFORE BLOG PAGE**
**AFTER BLOG PAGE**
=> Fixed the Blog page and Home page Navbar Elements

blogpage.html, blogpagestyle.css, style.css
Reverts Suchitra-Sahoo/AgriLearnNetwork#761
=> Revert "Fixed the Blog page and Home page Navbar Elements"

blogpagestyle.css
#759 
Fixed css in mobile view
before:
after:
=> Fixed footer css in mobile view

blogpage.html, scrollreveal.js
FIXES: #771 
https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/169196836/35b38f57-8d23-41af-9e05-61c8d4ef8497
=> scroll reveal effect added

faqpage.html
FIXES: #774 
Before:
https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/169196836/7d217e2a-894f-4e4a-8b07-956a34813fe9
After fixing :
https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/169196836/2d39716c-511d-4011-86a1-5a30b010d693
=> navbar links of FAQ page fixed

blogpage.html
I have added correct links in the "Resource Library" and "Contact us " section of the footer page. Now on clicking them, they navigate to their respective sections on the home page.
hey PA,
Please review the updated code and merge it. Thank You!
=> Fixed the broken links in the footer section of Blog Page!

login.css, login.html, login.js
#728 
Added login or register page using toggle feature on buttons.
And background image animation for page
https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/109607812/fcc0e311-9e37-4eda-a131-465351ad4ab7
check at this link:
https://hemav009.github.io/AgriLearnNetwork/
=> Added login/register page and background animation for the page

login.css, login.html, login.js
Reverts Suchitra-Sahoo/AgriLearnNetwork#796
=> Revert "Added login/register page and background animation for the page"

faqpage.html, index.html
Fixes: #747 
added  FAQ in footer of home page and made the footer links are active in FAQ page
https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/125258286/d0a6a960-f28d-4458-a53a-ac70e1caf54f
=> added  FAQ in footer of home page and made the footer links are active in FAQ page

login.css
#740 
Updated the login page background fro transition
- [ X ] Feature enhancement
https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/135994674/5e945843-dba3-4e4c-9016-07030cd90fd6
- [ X ] I have performed a self-review of my code
- [ X ] I have read and followed the Contribution Guidelines.
- [ X ] I have tested the changes thoroughly before submitting this pull request.
- [ X ] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [ X ] I have commented my code, particularly in hard-to-understand areas.
=> Updated login.css

blogpage.html
I have added the link to About Us section in the footer of the Blog Page.
Issue Number : #746 
=> Fixed the About Us link in the footer section of the Blog Page!

style.css
#799 
Fixed navbar CSS in mobile view
Before:
After :
=> Fixed navbar issue

style.css
Reverts Suchitra-Sahoo/AgriLearnNetwork#810
=> Revert "Fixed navbar issue"

index.html, login.css, login.html
The Feature of Google Login is added on the Login Page(login.html)
Since there is no Backend or Database connected to this website, this button will just allow to login and will redirect to home page without storing the details of the google account.
=> Add/Allow google Login #762

index.html, login.css, login.html
Reverts Suchitra-Sahoo/AgriLearnNetwork#795
=> Revert "Add/Allow google Login #762"

style.css
Reverts Suchitra-Sahoo/AgriLearnNetwork#822
=> Revert "fixed navbar issue "

login.css, login.html, login.js
#728 
added  login or sign-up and background animation to the page
- [] Bug fix
- [] Documentation update
- [] Other (specify): _______________
please check in login page 
https://hemav009.github.io/AgriLearnNetwork/
https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/109607812/3b7f155f-5ca5-4a69-8114-e0875c1bc232
=> added login or sign up and background animation to the page

faqpage.html, faqpagestyle.css
issue no #794
Add Scrollbar like home page also added Favicon to this page.
=> Faq Scrollbar like home page and added favicon

script.js
#802 
I have made some changes so that if one question is opened the rest of the opened ones will close.
https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/127978268/4eef2461-a2d5-4d3e-bd3e-9a04258fec8d
=> Changes in faq page

style.css
#799 
Fixed CSS of Navbar
- [] Feature enhancement
please merge the issue and add gssoc badge @Suchitra-Sahoo
=> Fixed CSS of navbar

style.css
Reverts Suchitra-Sahoo/AgriLearnNetwork#852
=> Revert "BUG: Footer "Quick Links" ul tag word gap is not good"

index.html, style.css
Fixed: #823
I have added a toggle mode to switch from light to dark. The default mode is light and it changes to dark mode when clicked. This feature enhances the website.
Light mode:
Dark mode:
=> Added the toggle mode

index.html, style.css
Fixes: #859 
Made the necessary changes to the toggle button to ensure proper alignment on small screens.
Large Screen:
https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/115869626/27966944-7ae0-4bd6-905e-01add04838fc
Small Screen:
https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/115869626/9ce8440a-8aba-4151-b8ea-74f4a2c48673
=> Fixed the toggle button

index.html, style.css
Reverts Suchitra-Sahoo/AgriLearnNetwork#869
=> Revert "Updated the Dark mode button"

index.html, style.css
#853
I improved the UI of the contact section which was merging with the background of the contact section.
#853 
Feat: Adding of some new feature in Contact Section
SS -
=> Improved the UI of contact section which was merging with the background.

blogpagestyle.css
issue no #828
Added scrollbar like home page.
Also add hover effects like home page in social icons.
https://www.loom.com/share/dad7320ebaa24a7d8ce07d81527503a0
=> Blog page scrollbar and social icons fix

style.css
#870  solved.
#870 
Feat: Navbar section anchor tag blinking effect is solved now.
Here I added blinking effect on the navbar anchor tag due to this effects navbar now looking attractive.
https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/136844498/0991b177-33f3-49d1-8279-be3cbe4951cf
=> Navbar section anchor tag blinking effect.

style.css
Reverts Suchitra-Sahoo/AgriLearnNetwork#879
=> Revert "Navbar section anchor tag blinking effect."

index.html, style.css
Fixes: #823 
Added the dark mode button and fixed it to toggle properly.
https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/115869626/9cf56b46-62fb-4d82-a78c-442070b01dce
https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/115869626/18b62c1a-961f-47c8-bfba-4fc1ddce0340
=> Solved mode issue

index.html, style.css
Reverts Suchitra-Sahoo/AgriLearnNetwork#878
=> Revert "Solved mode issue"

index.html, script.js, style.css
Fixes: #823 
Updated the dark mode for Contact Us page
https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/115869626/c42d452d-e27e-4c55-b796-da6aa18d17d8
https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/115869626/93694a79-196e-4030-86c1-5f8e8e40748a
=> Updated Dark mode

blogpage.html
Hello
I had made changes in date and time in blogpage.html
=> Date and time as been changed

blogpage.html
Hello 
I changed to the correct year in the blogpage
=> changed to the correct year

style.css
#870 solved.
#870 
Feat: Navbar section anchor tag blinking effect. #870
Here I added only blinking effects on the navbar anchor tag.
The options of navbar not getting blur on hovering and also the login option is not going out of navbar.
Video -
https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/136844498/40bdbfa8-47b5-4526-b28f-45cbcd46e343
=> Navbar section anchor tag blinking effect

index.html, style.css
Previous welcome div has a blur effect which makes glassy welcome div 
Now I Updated welcome div by enhancing it & added  glow effect to the text
https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/108344062/bfa50558-3fd9-4d5f-9959-0063b67ee9e3
d21-86f2838b2f9f)
https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/108344062/a2fa9584-427d-4c66-85e0-c0b61819e9cd
=> Updated welcome div by enhancing it & added  glow effect to the text #842

index.html, script.js, style.css
Reverts Suchitra-Sahoo/AgriLearnNetwork#901
=> Revert "#840 Issue resolved"

login.css
Solved the issue #904
I have fixed the login page and now the contents are properly aligned on the screen.
=> Fixed the login page

login.css
Reverts Suchitra-Sahoo/AgriLearnNetwork#905
=> Revert "Fixed the login page"

login.css, style.css
Fixes #904
Now the login page contents are properly aligned and on scrolling there is no overlapping between navbar and the container.
Removed the overlapping on scrolling between navbar and the main container. 
=> Login page without overlapping

login.css, style.css
Reverts Suchitra-Sahoo/AgriLearnNetwork#910
=> Revert "Login page without overlapping"

login.html, login.js
Closes #900 
I added the required code in the login.html and login.js file to ensure that the password visibility toggle button is  added in both password and confirm password on "Sign-in" section.
- [️✅] Feature enhancement
Screenshot
Video
https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/166159211/1aa9f840-7654-4646-9df7-115079f53830
- [✅] I have performed a self-review of my code
- [️✅] I have read and followed the Contribution Guidelines.
- [✅] I have tested the changes thoroughly before submitting this pull request.
- [️✅] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [  ] I have commented my code, particularly in hard-to-understand areas.
=> Addition of password visibility toggling button

login.css, login.html, login.js, style.css
Solved the issue #904
I have fixed the overlapping problem of the login page and the main container is now properly aligned on scroll as well.
https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/143121854/1e34dfc6-a10b-4975-a2a5-f280053f388d
=> Fixed the overlapping on scroll of login page.

login.css, login.html, login.js, style.css
Reverts Suchitra-Sahoo/AgriLearnNetwork#915
=> Revert "Fixed the overlapping on scroll of login page."

blogpage.html, buy_products.css, buy_products.html, buy_products.js, faqpage.html, faqpagestyle.css, index.html, login.html, style.css
closes issue #894
created a merchandised webpage for agricultural equipments. It also contains a mini cart which is movable.
The webpage is set up for both dark and light modes . Also i have included the links of the "buy products " webpage to all the other webpages including FAQ, blog, and index home page.
Kindly tell me if any changes required.
=> created a merchandised webpage for agricultural equipments

blogpage.html, blogpagestyle.css, buy_products.css, buy_products.html, buy_products.js, faqpage.html, faqpagestyle.css, index.html, style.css
issue #933 
the required changes were made , the hamburger menu was added . The background was changed so that it do not merge with nav bar . the dark mode was enhanced more.The login option was made to get inside the nav bar menu block in all the pages . also the cart is movable , so it can be dragged and move in the whole page.
=> Made the required changes in the "Merchandised webpage" 

blogpagestyle.css
#917 
I have added css code to animate the search icon for the page to look enhancing and adjusted the search for a great look.
https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/142327526/b75a354d-09d3-40f2-9019-354ada408cb0
Please approve.
=> Animated Icon 

faqpagestyle.css
BUG: Extra whitespace in faqs page #921
close #921
- removed extra whitespace from faqs page
=> removed extra whitespace from faqs page

blogpage.html, blogpagestyle.css, faqpage.html, faqpagestyle.css, index.html, style.css
Hello @Suchitra-Sahoo ,
Issue #906  is now fixed
once check it out and please add appropriate labels to it
There are different hover effect exists on quicklinks at footer section on Home ,blogs,FAQ pages.
Now it is fixed with a better hover effect which is applied to all the pages
https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/108344062/88125f8e-8d32-4586-88ff-d5115af7274d
=> Hover to quicklinks is added to all pages & FAQ is added to blog page #906

faqpagestyle.css, style.css
issue #945 
corrected the nav bar problem in the faq webpage also corrected the nav bar of main page which also had the same problem.
BEFORE:
AFTER:
=> corrected the nav bar problem

faqpagestyle.css
@Suchitra-Sahoo 
Feat: Make Faqs page responsive #922
close #922
- make faqs page responsive for mobile devices
=> make faqs page responsive

faqpage.html, faqpagestyle.css, script.js
Reverts Suchitra-Sahoo/AgriLearnNetwork#934
=> Revert "look of faq page"

buy_products.html
@Suchitra-Sahoo 
BUG: Missing FavIcon in buy_products.html #953
close #953
=> added favicon in `Buy_products` page

index.html, script.js, style.css
Resolved #721 
https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/117583791/56990320-e5bf-4521-81f7-e3d2250aea8d
- resolved the issue of sliding images
- resolved the issue of the multiple texts
- [ ✔️] Feature enhancement
- [✔️ ] I have performed a self-review of my code
- [ ✔️] I have read and followed the Contribution Guidelines.
- [✔️ ] I have tested the changes thoroughly before submitting this pull request.
- [✔️ ] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [✔️ ] I have commented my code, particularly in hard-to-understand areas.
=> Updated the sliding image

buy_products.html, cart.css, cart.html
@Suchitra-Sahoo 
Feat: Update the cart ui #952
close #952
- added cart ui
- make it responsive 
- new route `/cart.html`
=> Added beautiful `cart` ui

login.css
closes issue #926 
corrected the overlapping of nav bar and form slider in login page.
=> corrected the overlapping of nav bar and form slider in login page

login.css
Reverts Suchitra-Sahoo/AgriLearnNetwork#962
=> Revert "corrected the overlapping of nav bar and form slider in login page"

login.css
Reverts Suchitra-Sahoo/AgriLearnNetwork#963
=> Revert "Revert "corrected the overlapping of nav bar and form slider in login page""

faq/Expand-less-dark.svg, faq/Expand-more-dark.svg, faqpage.html, faqpagestyle.css
Closes issue #948 
Added dark mode in FAQ page. 
https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/121669832/093b7394-e3ec-4192-9363-0e653a6a8bb5
=> Feat: Added dark mode to FAQ.

blogpage.html, blogpagestyle.css
issue no #941
Added css in blogpagestyle.css like home page's backtotop button.
Delete previous Scrolltotop button's code.
=> Added BacktoTop in Blog page same as Home page

index.html
Hello Project Admin
I Added Emojis instead of Stars - Solved #947
Kindly Please go through this PR @Suchitra-Sahoo 
https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/161804629/d765bb13-bf9f-435d-aed8-952e32da5bf1
=> Added Rateus Form with Emoji

style.css
@Suchitra-Sahoo 
BUG: Resource library cards changed #951
close #951
=> resource library cards width

blogpage.html, blogpagestyle.css, buy_products.css, buy_products.html, faqpage.html, faqpagestyle.css, index.html, style.css
#966 
I have updated the footer by adding logo and some website detail to it
the previous footer
the new one
=> updated the footer

blogpage.html, blogpagestyle.css, buy_products.css, buy_products.html, faqpage.html, faqpagestyle.css, index.html, style.css
Reverts Suchitra-Sahoo/AgriLearnNetwork#988
=> Revert "updated the footer"

buy_products.css, buy_products.html
=> Fixed Checkout icon in products page

buy_products.css, buy_products.html
Reverts Suchitra-Sahoo/AgriLearnNetwork#994
=> Revert "Fixed Checkout icon in products page"

blogpage.html, buy_products.html, faqpage.html, index.html
Issue #985
added link of buy product in the quick links  . also changed the active content of "buy product" webpage
=> added link of buy product in the quick links 

style.css
=> Revert "Contact us enhance"

about/about.css, about/about.html, blogpage.html, buy_products.html, faqpage.html, index.html, login.html
fixes #891 
1. I have created separate page for about us.
2. About us page is responsive.
4. updated about us link in each html files.
5. removed about us section from index.html.
Kindly please let me know if any changes required!
=> Add about us page

blogpagestyle.css
issue fixed : #975  
https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/108344062/94ae1896-5b0e-4454-8951-553f8af8aff2
=> Navbar Position is fixed Properly

about/about.css
#1002 
I have changed the font as same as in the style.css
=> Changed the font of about page

index.html
Added subscribe to news letter
Added subscribe to news letter
Closes #1022 
=> Added subscribe to news letter

index.html
Reverts Suchitra-Sahoo/AgriLearnNetwork#1024
=> Revert "Added subscribe to news letter"

blog/blog.js, blog/blogpagestyle.css
Solves #1006
Now the navbar on the agro blogs page is similar to other pages with properly working hamburger icon.
=> Modified navbar of the AgroBlogs page.

blog/blog.js, blog/blogpagestyle.css
Reverts Suchitra-Sahoo/AgriLearnNetwork#1029
=> Revert "Modified navbar of the AgroBlogs page."

FAQS/faqpagestyle.css, buyproducts/buy_products.css, style.css
closes #1023 
Changed the navbar style on all pages so that it does not get overflown.
=> Navbar changes

FAQS/faqpagestyle.css, buyproducts/buy_products.css, style.css
Reverts Suchitra-Sahoo/AgriLearnNetwork#1035
=> Revert "Navbar changes"

login/login.css, login/login.html
fixes #1034 
Feat/ add hovering effect to social icone of login sign up page and fixed the position of items when hovering 
BEFORE : 
https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/159682348/2e429ebf-f0ab-462c-9c1d-c90f240e7b78
AFTER : 
https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/159682348/806821a3-dcba-48b4-b524-e9d8d0734818
it will look good in footer section also .
=> Feat/ add hovering effect to social icone of login sign up page and fixed the position of items when hovering 

index.html, testimonials/testimonials.css
=> Revert "Testimonial section made resposive"

style.css
Footer and its content are aligned
for reference :- 
@Suchitra-Sahoo please have a look
#939
=> Footer Alignment

testimonials/testimonials.css, testimonials/testimonials.js
Fixes #1043
**Added Responsiveness.
Fix working and position of left and right button.
Fix Scrollbar hover it is due to duplicate code in testimonials section.
Responsive in heading Testimonials.**
=> Responsivenss testimonials fix scrollbar fix left and right button

FAQS/faqpage.html, about/about.html, buyproducts/buy_products.html, index.html
Reverts Suchitra-Sahoo/AgriLearnNetwork#1040
=> Revert "Bot optimised"

FAQS/faqpagestyle.css, buyproducts/buy_products.css, style.css
Closes #1023 
Final Pr for making navbar changes and adding proper padding
=> Navbar padding changed

FAQS/faqpagestyle.css, buyproducts/buy_products.css, style.css
Reverts Suchitra-Sahoo/AgriLearnNetwork#1053
=> Revert "Navbar padding changed"

blog/blog.js, blog/blogpagestyle.css
Fixes #1006
On click of the hamburger icon navbar is displayed for smaller screens and now the navbar is not overflowing.This navbar looks similar to the one in other pages.
https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/143121854/f9cab767-9b26-448b-a8d0-8ffa30c00bfa
=> Update navbar of Blogs page.

about/about.html, buyproducts/buy_products.html
Fixes #1060
Added scrolling to top behavior in about and buy products page.
Stoped page reloading.
https://www.loom.com/share/4cba3f31169d4726805401e28bf354da
=> Scoll to top behavior added stoped loading

buyproducts/buy_products.js
#1056 
I have corrected the issue of the total in the cart feature.
- [*] Bug fix
before (when issue was present)
when issue is solved
=> corrected the total in the cart feature

cursor/script.js, cursor/style.css
Reverts Suchitra-Sahoo/AgriLearnNetwork#1065
=> Revert "Cursor Lag Resolved"

cursor/script.js, cursor/style.css
Reverts Suchitra-Sahoo/AgriLearnNetwork#1069
=> Revert "Revert "Cursor Lag Resolved""

index.html, style.css
Issue no: #893 
I have changed the ui of feedback form . 
- [ X] Feature enhancement
- [ X] I have performed a self-review of my code
- [ X] I have read and followed the Contribution Guidelines.
- [ X] I have tested the changes thoroughly before submitting this pull request.
- [X ] I have provided relevant issue numbers, screenshots, and videos after making the changes.
=> updated ui of feedback form

index.html, style.css
Reverts Suchitra-Sahoo/AgriLearnNetwork#1078
=> Revert "updated ui of feedback form"

style.css
Closes issue: #1018 
I have changed the website's default font to poppins
=> Poppins font added

style.css
Reverts Suchitra-Sahoo/AgriLearnNetwork#1073
=> Revert "Poppins font added"

index.html, style.css
fixes #1042 
Added Floating Social Media Iconbar on Homepage
https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/146121869/93a44887-8d8e-4b0f-a0a5-6d7812fd7f6c
=>  Added Floating Social Media Iconbar on Homepage

blog/blogpagestyle.css, index.html, style.css
Related to PR https://github.com/Suchitra-Sahoo/AgriLearnNetwork/pull/1073
I have added the font to blog posts.
Kindly let me know if there are any changes to be made.
=> font added to blogs

FAQS/faqpagestyle.css, about/about.css, buyproducts/buy_products.css, index.html, login/login.css, style.css, testimonials/testimonials.css
Linked to : https://github.com/Suchitra-Sahoo/AgriLearnNetwork/pull/1088
Font added to all pages and space added in between the header
- Space added between AgriLearnNetwork and Home in the header.
- Font added
=> font added to all pages

FAQS/faqpagestyle.css, about/about.css, buyproducts/buy_products.css, index.html, login/login.css, style.css, testimonials/testimonials.css
Reverts Suchitra-Sahoo/AgriLearnNetwork#1092
=> Revert "font added to all pages"

buyproducts/buy_products.css, buyproducts/buy_products.html, buyproducts/buy_products.js, buyproducts/products.json
closes #1041 
- Added JSON file to store product data
- Added highlights section
- On hover highlights about products appear
- Added JS to fetch data and display through HTML
- Added Search Bar
- Modified Cart UI
- Improved visibility of texts
=> [feature]Product page Improvement

buyproducts/buy_products.css, buyproducts/buy_products.html, buyproducts/buy_products.js
#1057 
I have added the search bar and also the heading "Agroproducts" to the page.
https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/152094228/a6277f0a-2b77-4a21-b7aa-9116f1da5e1c
There is a humble request of considering this PR of level2.
=> added search bar to the buy product page

testimonials/privacypolicy.html, testimonials/termsandconditions.html
Hey @Suchitra-Sahoo,
This PR closes issue #1077 
- I Added Circular Cursor in both the pages
- Fixed the spacing between card and footer in both the pages
- [x ] I have commented my code, particularly in hard-to-understand areas.
=> Resolved - Added Circular Cursor and Fixed Spacing ➕

FAQS/faqpagestyle.css, blog/blogpage.html, blog/blogpagestyle.css, buyproducts/buy_products.css, style.css
Basically i have enhanced the Navigation Bar.Changes i have done:
1] Added the Hover underline effect as shown in attached video which looks super cool.
2] Had aligned the login button in all section as it was unaligned as i mentioned in the issue.
and add the cart button as it was mentioned in my issue.
Overall i had done these many changes in which the nav bar looks perfect and aligned.
I have attached both Video and Screenshot below.
=> Enhanced the Nav bar by aligning the login button and adding hover underline effect.

FAQS/faqpage.html, about/about.html, blog/blogpage.html, index.html, login/login.html
Hey @Suchitra-Sahoo  ,
issue closes #1086 
I have added the Scroll down progress bar in All pages of the website
Please take a look and review it.
=> Added "Scroll Down Progress Bar" To The website 

buyproducts/buy_products.html, buyproducts/buy_products.js
#1102
Now the checkout button on cart section works properly.
https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/143121854/1577359a-e1c0-4659-98b1-d58dc94743c8
=> Added functionality to the Checkout button on the cart section .

FAQS/faqpage.html, FAQS/faqpagestyle.css, about/about.html, blog/blogpage.html, blog/blogpagestyle.css, buyproducts/buy_products.css, buyproducts/buy_products.html, index.html, login/login.html, privacypolicy.html, style.css, termsandconditions.html
fixes #1047 
on hovering it changes to its actual colour IN ALL THE PAGES OF THE WEBSITE .
https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/159682348/201bc6e4-3540-4195-95da-2c87ff3fea29
=> add hovering effect in social icons

FAQS/faqpage.html, Scrollbar/scrollbar.css, Scrollbar/scrollbar.js, about/about.html, blog/blogpage.html, buyproducts/buy_products.html, index.html, login/login.html, testimonials/privacypolicy.html, testimonials/termsandconditions.html
Hey @Suchitra-Sahoo ,
closes #1127 
Added "Scroll Down Progress Bar" by making separate folder of scroll progress bar
Please take a look and review it.
=> Added "Scroll Down Progress Bar" 

buyproducts/buy_products.css, buyproducts/buy_products.html, buyproducts/buy_products.js
solves issue: #1057 
solves issue raised in pull request: #1111 
I have added the search bar in the buy products page and also heading.
https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/152094228/c0b0400f-28db-4cc7-94cd-db99955d6b78
Now I hope the search bar has no issues further.
=> #added search bar

index.html, style.css
Solved issue  #1139 
I have changed the Twitter logo 
=> Modified the Twitter logo

blog/blogpage.html, blog/blogpagestyle.css
Solves #1123
Fixed the overlapping of dates with the text on some of the cards in the AgroBlogs page .
=> Fixed the overlapping of dates with text on the blogs page .

blog/blogpage.html, blog/blogpagestyle.css
Reverts Suchitra-Sahoo/AgriLearnNetwork#1152
=> Revert "Fixed the overlapping of dates with text on the blogs page ."

FAQS/faqpage.html, Scrollbar/scrollbar.css, blog/blogpage.html, buyproducts/buy_products.html, login/login.html
#1138
I have added progress bar on all the pages similar to the home page .
=> Added progress bar on all the pages .

FAQS/faqpagestyle.css
Solves #1161
I have added transition effect on scroll of the navbar on FAQ page similar to navbar on other pages .
https://github.com/user-attachments/assets/73d4b0e1-ceb6-4914-98b1-db2fa1ea8ffb
=> Added transition on scroll of navbar on FAQ page similar to other pages .

buyproducts/buy_products.css, buyproducts/buy_products.html, buyproducts/buy_products.js
Fixed #1170 
I added Transition which looks cool and UI of cart in which button is transformed
- [ X] Feature enhancement
https://github.com/user-attachments/assets/d1bb0d9b-cda1-4597-b172-f4185c94b640
- [X ] I have performed a self-review of my code
- [ X] I have read and followed the Contribution Guidelines.
- [ X] I have tested the changes thoroughly before submitting this pull request.
- [ X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [ X] I have commented my code, particularly in hard-to-understand areas.
[Include …
=> Cart UI Transition Added

buyproducts/buy_products.css, buyproducts/buy_products.html, buyproducts/buy_products.js
Reverts Suchitra-Sahoo/AgriLearnNetwork#1190
=> Revert "Cart UI Transition Added"

index.html, style.css
Issue Number : #1178
I had enhaced the Feedback form by:
-> Added glow effect in the feedback form.
-> Enhanced the closing button by adding revolving effect and changing the look of it.
-> Corrected the closing button overlapping in mobile view .
-> Changes in stars in which all stars glow according to moving cursor.
-> Added glow effect in submit as well as input text buttons.
-> Added effect in the "Rate you Experience" as shown in video.
Thank You!
- [] Bug fix
Current Feedback Form Video:
https://github.com/user-attachments/assets/08073da0-d6e3-40d5-9ecd-9a8e166ccaac
After changes:
https://github.com/user-attachments/assets/1487f201-cda5-4565-ac71-c45d50606f41
=> [STYLE] Enhanced the Feedback Section.

buyproducts/buy_products.css, buyproducts/buy_products.html, buyproducts/buy_products.js
Reverts Suchitra-Sahoo/AgriLearnNetwork#1166
=> Revert "update cart ui and make seperate route and make it functional"

buyproducts/buy_products.css, buyproducts/buy_products.html, script.js
#1144 
Fixed the issue of **login button changing to register** on hovering of mouse. Also made the buy products page style consistent with the other pages by **fixing the navbar** and adding the **hover functionality** of buttons with the **cursor styling**.
On hover (index.html)
Buy Products page - 
Made navbar same as other pages for consistency and added the cursor effect also.
Not hovering:
On hover:
=> Fixed login button and made buy page consistent

login/login.css, login/login.html
#1165 
I fixed the minor issues in login page which were making the UI look unattractive.
=> Fix login page minor errors

login/login.css, login/login.html, login/login.js
issue number: #764 
This PR contains the forgot-password page. When 'Forget Your Password?' is clicked on login page, user is redirected to 'forgot password page'. User can enter his/her email.  User can navigate to login page by clicking 'back to login'.
=> #764: Add forgot password page.

buyproducts/buy_products.html, buyproducts/checkout.html
Solves #1177
I have added ₹ in place of Rupee in Buy Products page and in place of $ in Make Payment page . I have also added this ₹  in the cart section .
=> Added ₹ in place of Rupee in Buy Products page and Make Payment page .

blog/blogpage.html, blog/blogpagestyle.css
#1123
Fixed the overlapping of dates with texts on the cards on the blogs page for various kinds of screens .
=> Fixed overlapping of dates on blog page also in responsive view .

buyproducts/checkout.html
Reverts Suchitra-Sahoo/AgriLearnNetwork#1232
=> Revert "payment method added in checkout page"

Contributors/contributor.css, Contributors/contributor.html, Contributors/contributor.js, FAQS/faqpage.html, FAQS/faqpagestyle.css, about/about.html, blog/blogpage.html, blog/blogpagestyle.css, buyproducts/buy_products.css, buyproducts/buy_products.html, index.html, login/login.html
Issue: #1137
I developed and optimized the Contributor Page, focusing on enhancing user experience, responsiveness, and performance.
The project involved the following key tasks:
1. Page Development:
a. Design and Layout: Crafted a visually appealing and user-friendly layout for the Contributor Page, ensuring consistency 
with the overall theme of the website.
b. Fetching Contributor Data: Implemented functionality to fetch and display contributor data from the GitHub API. This 
involved asynchronous data fetching, error handling for rate limits, and dynamically generating contributor cards.
c. DOM Manipulation: Optimized the DOM manipulation process to reduce reflow and repaint operations, resulting in 
smoother and faster rendering of contributor information.
d. Caching: Added local …
=> Added Contributors page

blog/blogpage.html, blog/blogpagestyle.css
Reverts Suchitra-Sahoo/AgriLearnNetwork#1241
=> Revert "Added toggle button to the blog webpage and respective colour changing as per theme"

login/login.css, login/login.html, login/login.js
fixes #1210 
When User signs in if a pop up comes , it would look good , and user will get ensured that signin is successful
https://github.com/user-attachments/assets/0dc9f8e0-9dca-4a01-befa-56c505753885
=> Added popup for signin successful

Contributors/contributor.css, Contributors/contributor.html
Issue: #1137
I developed and optimized the Contributor Page, focusing on enhancing user experience, responsiveness, and performance.
The project involved the following key tasks:
1. Page Development:
a. Design and Layout: Crafted a visually appealing and user-friendly layout for the Contributor Page, ensuring consistency 
with the overall theme of the website.
b. Fetching Contributor Data: Implemented functionality to fetch and display contributor data from the GitHub API. This 
involved asynchronous data fetching, error handling for rate limits, and dynamically generating contributor cards.
c. DOM Manipulation: Optimized the DOM manipulation process to reduce reflow and repaint operations, resulting in 
smoother and faster rendering of contributor information.
d. Caching: Added local …
=> Added Contributor' page

Contributors/contributor.css, Contributors/contributor.html
Reverts Suchitra-Sahoo/AgriLearnNetwork#1238
=> Revert "Added Contributor' page"

about/about.html, buyproducts/buy_products.html
Issue #1229 solved
Added the upward arrow on the scroll to top button in the 'buy products' page.
=> Added scroll-to-top arrow button

Contributors/contributor.css
Fixes #1246
Modified the contributor page by changing their shape and also added hover effects .
https://github.com/user-attachments/assets/aaf4c852-b8ed-4e8e-85b3-a43bf38a2e4e
=> Added hover effects on the contributors page .

Contributors/contributor.css, Contributors/contributor.html
Fixes #1201 
Since the privacy and T&C page were assigned again so I have added dark mode on contributor page , in which this feature was  absent .
Added toggle effect on the Contributor page .
https://github.com/user-attachments/assets/1a33be1f-c281-4a87-b912-2ebd36ab7fc0
=> Added dark mode toggle effect on the Contributor page .

testimonials/privacypolicy.html, testimonials/termsandconditions.html
Fixes #1216
Added Dark Mode also there is bugs in terms and privacy pages.
Link Cursor not work / Backtotop not visible / in privacy page footer missing all that issues solved.
https://www.loom.com/share/50e344f3d30941a98ce4a40d96b8e492
https://www.loom.com/share/7410f230697a4744a768aaf70d5e2d5a
=> Privacy/Term page darkmode/cursor/backtotop/ in privacy footer addition

buyproducts/checkout.html
#1167 
i added  paypal as well as credit card as a payment method
=> solve revert issue

buyproducts/checkout.html
Reverts Suchitra-Sahoo/AgriLearnNetwork#1237
=> Revert "solve revert issue"

Contributors/contributor.css, Contributors/contributor.html, Contributors/contributor.js
Enhancement in Contributor page. #1259
**Fix Navbar.**
**Added New Style for Contributor cards.**
**Faster data fetching.**
**Attractive Cards with hover effects.**
**Added Responsiveness.**
=> Fix Contributors issues and Enhance it

Contributors/contributor.css, Contributors/contributor.html, Contributors/contributor.js
Reverts Suchitra-Sahoo/AgriLearnNetwork#1289
=> Revert "Fix Contributors issues and Enhance it"

blog/blogpagestyle.css, index.html, login/login.css, login/login.html, login/login.js, testimonials/testimonials.css
#1265 
1. Validation added to both sign in and sign up
2. Toggle card background changed
3. Container bug resolved
4. pop up added succesfully
https://github.com/user-attachments/assets/69340bf9-579d-4e65-af39-8e070f1bc218
=> BUG: Log in page validation fixed

Contributors/contributor.css, Contributors/contributor.html
Solves #1247
Added a progress bar and scroll effects on navbar of contributor page similar to other pages .
https://github.com/user-attachments/assets/1390a0a3-1ee2-4c71-a1f6-c66000d39ef3
I have also updated the font style of the heading page to the base font style Poppins .
=> Added a progress bar and scroll effects on navbar of contributor page .

buyproducts/buy_products.css, buyproducts/buy_products.html
#1205  
1.  changed cards looks and positioning
2.  add added suitable colors in dark and light mode
=> Buy_product page UI 

style.css
Reverts Suchitra-Sahoo/AgriLearnNetwork#1295
=> Revert "Enhanced Separation in Quick Links Section"
